version: 2.1

executors:
  notificasaude-executor:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/notificasaude

jobs:
  build-backend:
    executor: notificasaude-executor
    steps:
      - checkout
      - restore_cache:
          key: notificasaude/backend-{{ checksum "backend/yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/backend:/usr/src/app -w /usr/src/app node:13 yarn install
      - save_cache:
          paths:
            - ~/notificasaude/backend/node_modules
          key: notificasaude/backend-{{ checksum "backend/yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - notificasaude/backend
  deploy-backend:
    executor: notificasaude-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: docker run --rm -it -v ${PWD}/backend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 npx sequelize-cli db:migrate
      - run: cd backend && docker build -t notificasaude/backend -f Dockerfile .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag notificasaude/backend registry.heroku.com/covid19-db1-backend/web:latest
      - run: docker push registry.heroku.com/covid19-db1-backend/web:latest
      - run: sudo snap install --classic heroku
      - run: heroku container:login
      - run: heroku container:release web --app covid19-db1-backend
  deploy-backend-qa-aws:
    executor: notificasaude-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup:
          profile-name: default
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend
      - run: cd backend && docker build -t notificasaude/backend:latest .
      - run: docker tag notificasaude/backend:latest 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa
  deploy-backend-prod-aws:
    executor: notificasaude-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup:
          profile-name: default
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend
      - run: docker pull 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa
      - run: docker tag 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:latest
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:latest

  build-frontend:
    executor: notificasaude-executor
    steps:
      - checkout
      - restore_cache:
          key: notificasaude/frontend-{{ checksum "frontend/yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app node:13 yarn install
      - save_cache:
          paths:
            - ~/notificasaude/frontend/node_modules
          key: notificasaude/frontend-{{ checksum "frontend/yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 yarn test:unit
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - notificasaude/frontend
  deploy-frontend:
    executor: notificasaude-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cd frontend && docker build -t notificasaude/frontend .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag notificasaude/frontend registry.heroku.com/covid19-db1-frontend/web:latest
      - run: docker push registry.heroku.com/covid19-db1-frontend/web:latest
      - run: sudo snap install --classic heroku
      - run: heroku container:login
      - run: heroku container:release web --app covid19-db1-frontend

orbs:
  aws-cli: circleci/aws-cli@1.0.0

workflows:
  version: 2.0
  covid19:
    jobs:
      - build-backend
      - build-frontend
      - deploy-backend:
          requires:
            - build-backend
          filters:
            branches:
              only:
              - master
              - feature/terraform
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
              - master
      - deploy-backend-qa-aws:
          requires:
            - deploy-backend
          filters:
            branches:
              only:
              - master
              - feature/terraform
      - deploy-backend-prod-aws:
          requires:
            - deploy-backend-qa-aws
          filters:
            branches:
              only:
              - master
              - feature/terraform
