version: 2
jobs:
  backend:
    working_directory: ~/contra-covid19/backend

    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout:
          path: ~/contra-covid19

      - restore_cache:
          key: contra-covid19/backend-{{ checksum "yarn.lock" }}
      
      - run: docker run --rm -it -v ${PWD}:/usr/src/app -w /usr/src/app node:13 yarn install

      - save_cache:
          paths:
            - ~/contra-covid19/backend/node_modules
          key: contra-covid19/backend-{{ checksum "yarn.lock" }}

      - run: docker run --rm -it -v ${PWD}:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 npx sequelize-cli db:migrate

      - run: docker build -t contra-covid19/backend .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag contra-covid19/backend registry.heroku.com/covid19-db1-backend/web
      - run: docker push registry.heroku.com/covid19-db1-backend/web

  frontend:
    working_directory: ~/contra-covid19/frontend

    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout:
          path: ~/contra-covid19

      - restore_cache:
          key: contra-covid19/frontend-{{ checksum "yarn.lock" }}
      
      - run: docker run --rm -it -v ${PWD}:/usr/src/app -w /usr/src/app node:13 yarn install

      - save_cache:
          paths:
            - ~/contra-covid19/frontend/node_modules
          key: contra-covid19/frontend-{{ checksum "yarn.lock" }}

      - run: docker run --rm -it -v ${PWD}:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 yarn build

      - run: docker build -t contra-covid19/frontend .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag contra-covid19/frontend registry.heroku.com/covid19-db1-frontend/web
      - run: docker push registry.heroku.com/covid19-db1-frontend/web

workflows:
  version: 2
  covid19:
    jobs:
      - backend
      - frontend