version: 2
jobs:
  build:
    working_directory: ~/contra-covid19/backend

    branches:
      only:
        feature/ci

    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout:
          path: ~/contra-covid19

      - restore_cache:
          key: contra-covid19/backend-{{ checksum "yarn.lock" }}
      
      - run: docker run --rm -it -v ${PWD}:/usr/src/project node:13 yarn install

      - save_cache:
          paths:
            - ~/contra-covid19/backend/node_modules
          key: contra-covid19/backend-{{ checksum "yarn.lock" }}

      - run: docker run --rm -it -v ${PWD}/backend:/usr/src/project node:13 npx sequelize-cli db:migrate

      - run: docker build -t contra-covid19/backend .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag contra-covid19/backend registry.heroku.com/covid19-db1-backend/web
      - run: docker push registry.heroku.com/covid19-db1-backend/web
