version: 2.1

executors:
  covid19-executor:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  build-backend:
    executor: covid19-executor
    working_directory: ~/contra-covid19
    steps:
      - checkout
      - restore_cache:
          key: contra-covid19/backend-{{ checksum "yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}:/usr/src/app -w /usr/src/app node:13 yarn install
      - save_cache:
          paths:
            - ~/contra-covid19/backend/node_modules
          key: contra-covid19/backend-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/contra-covid19
          paths:
            - backend
  deploy-backend:
    executor: covid19-executor
    working_directory: ~/contra-covid19
    steps:
      - run: ls ~
      - run: ls ~/contra-covid19
      - run: ls ~/contra-covid19/backend
      - attach_workspace:
          at: ~/contra-covid19
      - run: ls ~
      - run: ls ~/contra-covid19
      - run: ls ~/contra-covid19/backend
      - run: docker run --rm -it -v ${PWD}/backend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 npx sequelize-cli db:migrate
      - run: docker build -t contra-covid19/backend -f backend/Dockerfile .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag contra-covid19/backend registry.heroku.com/covid19-db1-backend/web
      - run: docker push registry.heroku.com/covid19-db1-backend/web

  build-frontend:
    executor: covid19-executor
    working_directory: ~/contra-covid19/frontend
    steps:
      - checkout
      - restore_cache:
          key: contra-covid19/frontend-{{ checksum "yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app node:13 yarn install
      - save_cache:
          paths:
            - ~/contra-covid19/frontend/node_modules
          key: contra-covid19/frontend-{{ checksum "yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 yarn build
      - persist_to_workspace:
          root: ~/contra-covid19
          paths:
            - frontend
  deploy-frontend:
    executor: covid19-executor
    working_directory: ~/contra-covid19/frontend
    steps:
      - attach_workspace:
          at: ~/contra-covid19/frontend
      - run: docker build -t contra-covid19/frontend -f frontend/Dockerfile .
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker tag contra-covid19/frontend registry.heroku.com/covid19-db1-frontend/web
      - run: docker push registry.heroku.com/covid19-db1-frontend/web

workflows:
  version: 2.0
  covid19:
    jobs:
      - build-backend
      - build-frontend
      - deploy-backend:
          requires:
            - build-backend
          filters:
            branches:
              only:
              - master
              - feature/ci
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
              - master
              - feature/ci
