version: 2.1

executors:
  notificasaude-executor:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/notificasaude

jobs:
  build-backend:
    executor: notificasaude-executor
    steps:
      - checkout
      - restore_cache:
          key: notificasaude/backend-{{ checksum "backend/yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/backend:/usr/src/app -w /usr/src/app node:13 yarn install
      - save_cache:
          paths:
            - ~/notificasaude/backend/node_modules
          key: notificasaude/backend-{{ checksum "backend/yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - notificasaude/backend
  deploy-backend-qa-aws:
    executor: notificasaude-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup:
          profile-name: default
      - run: $(aws ecr get-login --registry-ids 127682629527 --region us-east-1 --no-include-email)
      - run: cd backend && docker build -t notificasaude/backend:latest .
      - run: docker tag notificasaude/backend:latest 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa
      - aws-ecs/run-task:
          cluster: notificasaude-qa
          task-definition: notificasaude-qa-backend
          awsvpc: false
          launch-type: EC2
          started-by: 'CircleCI << pipeline.number >>'
  deploy-backend-prod-aws:
    executor: notificasaude-executor
    steps:
      - aws-cli/setup:
          profile-name: default
      - run: $(aws ecr get-login --registry-ids 127682629527 --region us-east-1 --no-include-email)
      - run: docker pull 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa
      - run: docker tag 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:qa 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:latest
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/backend:latest
      - aws-ecs/run-task:
          cluster: notificasaude-prod
          task-definition: notificasaude-prod-backend
          awsvpc: false
          launch-type: EC2
          started-by: 'CircleCI << pipeline.number >>'

  build-frontend:
    executor: notificasaude-executor
    steps:
      - checkout
      - restore_cache:
          key: notificasaude/frontend-{{ checksum "frontend/yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app node:13 yarn install
      - save_cache:
          paths:
            - ~/notificasaude/frontend/node_modules
          key: notificasaude/frontend-{{ checksum "frontend/yarn.lock" }}
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 yarn test:unit
      - run: docker run --rm -it -v ${PWD}/frontend:/usr/src/app -w /usr/src/app -e NODE_ENV=$NODE_ENV node:13 yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - notificasaude/frontend
  deploy-frontend-qa-aws:
    executor: notificasaude-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup:
          profile-name: default
      - run: $(aws ecr get-login --registry-ids 127682629527 --region us-east-1 --no-include-email)
      - run: cd frontend && docker build -t notificasaude/frontend:latest .
      - run: docker tag notificasaude/frontend:latest 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/frontend:qa
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/frontend:qa
      - aws-ecs/run-task:
          cluster: notificasaude-qa
          task-definition: notificasaude-qa-frontend
          awsvpc: false
          launch-type: EC2
          started-by: 'CircleCI << pipeline.number >>'
  deploy-frontend-prod-aws:
    executor: notificasaude-executor
    steps:
      - aws-cli/setup:
          profile-name: default
      - run: $(aws ecr get-login --registry-ids 127682629527 --region us-east-1 --no-include-email)
      - run: docker pull 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/frontend:qa
      - run: docker tag 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/frontend:qa 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/frontend:latest
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/frontend:latest
      - aws-ecs/run-task:
          cluster: notificasaude-prod
          task-definition: notificasaude-prod-frontend
          awsvpc: false
          launch-type: EC2
          started-by: 'CircleCI << pipeline.number >>'

  deploy-keycloak-qa-aws:
    executor: notificasaude-executor
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: $(aws ecr get-login --registry-ids 127682629527 --region us-east-1 --no-include-email)
      - run: cd keycloak && docker build -t notificasaude/keycloak:latest .
      - run: docker tag notificasaude/keycloak:latest 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/keycloak:qa
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/keycloak:qa
      - aws-ecs/run-task:
          cluster: notificasaude-qa
          task-definition: notificasaude-qa-keycloak
          awsvpc: false
          launch-type: EC2
          started-by: 'CircleCI << pipeline.number >>'
          group: service:notificasaude-qa-keycloak
  deploy-keycloak-prod-aws:
    executor: notificasaude-executor
    steps:
      - aws-cli/setup:
          profile-name: default
      - run: $(aws ecr get-login --registry-ids 127682629527 --region us-east-1 --no-include-email)
      - run: docker pull 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/keycloak:qa
      - run: docker tag 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/keycloak:qa 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/keycloak:latest
      - run: docker push 127682629527.dkr.ecr.us-east-1.amazonaws.com/notificasaude/keycloak:latest
      - aws-ecs/run-task:
          cluster: notificasaude-prod
          task-definition: notificasaude-prod-keycloak
          awsvpc: false
          launch-type: EC2
          started-by: 'CircleCI << pipeline.number >>'

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws-ecs: circleci/aws-ecs@1.1.0

workflows:
  version: 2.0
  notificasaude:
    jobs:
      - build-backend
      - deploy-backend-qa-aws:
          requires:
            - build-backend
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform
      - update-backend-prod-aws:
          type: approval
          requires:
            - deploy-backend-qa-aws
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform
      - deploy-backend-prod-aws:
          requires:
            - update-backend-prod-aws
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform

      - build-frontend
      - deploy-frontend-qa-aws:
          requires:
            - build-frontend
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform
      - update-frontend-prod-aws:
          type: approval
          requires:
            - deploy-frontend-qa-aws
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform
      - deploy-frontend-prod-aws:
          requires:
            - update-frontend-prod-aws
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform

      - deploy-keycloak-qa-aws:
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform
      - update-keycloak-prod-aws:
          type: approval
          requires:
            - deploy-keycloak-qa-aws
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform
      - deploy-keycloak-prod-aws:
          requires:
            - update-keycloak-prod-aws
          filters:
            branches:
              only:
              - master
              - feature/ci
              - feature/terraform